#![cfg(feature = "patched-tls")]

use btls::aead::{AeadCtx, Algorithm};
use std::ffi::c_void;

extern "C" {
    fn EVP_aead_aes_128_ccm() -> *const c_void;
    fn EVP_aead_aes_256_ccm() -> *const c_void;
    fn EVP_aead_aes_128_ccm_8() -> *const c_void;
    fn EVP_aead_aes_256_ccm_8() -> *const c_void;
}

#[test]
fn ccm_matches_independent_openssl_vectors_at_every_scatter_boundary() {
    // Independent OpenSSL-backed cryptography.hazmat.primitives.ciphers.aead
    // AESCCM(key, tag_length).encrypt(nonce, plaintext, aad) generated these
    // vectors. None were generated by the patched backend under test.
    let cases = [
        (
            16,
            16,
            EVP_aead_aes_128_ccm as unsafe extern "C" fn() -> *const c_void,
            "60f6f480318441db7e8c0fac150db5f21ecfa6b7ca500a2b5f0430fcebf6fe0519d45b0a2ecca2d7",
        ),
        (
            16,
            8,
            EVP_aead_aes_128_ccm_8,
            "60f6f480318441db7e8c0fac150db5f21ecfa6b7ca500a2bdac4f0f15c8d0bd8",
        ),
        (
            32,
            16,
            EVP_aead_aes_256_ccm,
            "32f3bc23153b0c0918d3ed025d36de45538cd32d1a133509fafeea9f99a5c0fc9a0e846368cec6e2",
        ),
        (
            32,
            8,
            EVP_aead_aes_256_ccm_8,
            "32f3bc23153b0c0918d3ed025d36de45538cd32d1a133509a6cb39d0cd36c260",
        ),
    ];
    let nonce: Vec<u8> = (16..28).collect();
    let aad = hex::decode("1703030031").unwrap();
    // The final bytes model TLS 1.3's inner content type and padding.
    let plaintext = b"CCM split plaintext\x00\xff\x17\x00\x00";
    for (key_len, tag_len, function, expected_hex) in cases {
        // SAFETY: these FFI functions return immutable static AEAD descriptors.
        let algorithm = unsafe { Algorithm::from_ptr(function().cast()) };
        assert_eq!(algorithm.key_length(), key_len);
        assert_eq!(algorithm.nonce_len(), 12);
        assert_eq!(algorithm.max_tag_len(), tag_len);
        let key: Vec<u8> = (0..key_len as u8).collect();
        let ctx = AeadCtx::new_default_tag(&algorithm, &key).unwrap();
        assert!(AeadCtx::new(&algorithm, &key, tag_len - 1).is_err());
        let expected = hex::decode(expected_hex).unwrap();
        // Includes empty main input, empty extra input and unaligned boundaries.
        for split in 0..=plaintext.len() {
            let mut main = plaintext[..split].to_vec();
            let extra = &plaintext[split..];
            let mut suffix = vec![0; extra.len() + tag_len];
            assert_eq!(ctx.tag_len(main.len(), extra.len()).unwrap(), suffix.len());
            let written = ctx
                .seal_scatter(&nonce, &mut main, &mut suffix, Some(extra), &aad)
                .unwrap();
            main.extend_from_slice(written);
            assert_eq!(
                main, expected,
                "key={key_len}, tag={tag_len}, split={split}"
            );
            let mut ciphertext = main[..plaintext.len()].to_vec();
            ctx.open_gather(&nonce, &mut ciphertext, &main[plaintext.len()..], &aad)
                .unwrap();
            assert_eq!(ciphertext, plaintext);
        }
        for mutation in 0..4 {
            let mut ciphertext = expected[..plaintext.len()].to_vec();
            let mut tag = expected[plaintext.len()..].to_vec();
            let mut wrong_aad = aad.clone();
            let mut wrong_nonce = nonce.clone();
            match mutation {
                0 => ciphertext[0] ^= 1,
                1 => tag[0] ^= 1,
                2 => wrong_aad[0] ^= 1,
                _ => wrong_nonce[0] ^= 1,
            }
            assert!(ctx
                .open_gather(&wrong_nonce, &mut ciphertext, &tag, &wrong_aad)
                .is_err());
            // The EVP wrapper must not expose unauthenticated plaintext.
            assert!(ciphertext.iter().all(|b| *b == 0));
        }
        let mut ciphertext = expected[..plaintext.len()].to_vec();
        assert!(ctx
            .open_gather(
                &nonce,
                &mut ciphertext,
                &expected[plaintext.len()..expected.len() - 1],
                &aad
            )
            .is_err());
        let mut plaintext_copy = plaintext.to_vec();
        let mut tag = vec![0; tag_len];
        assert!(ctx
            .seal_in_place(&nonce[..11], &mut plaintext_copy, &mut tag, &aad)
            .is_err());
    }
}
