//! X448 provider for the patched backend. The pinned crrl implementation uses
//! a fixed 448-step Montgomery ladder with constant-time field operations.
//! BoringSSL owns randomness, transcript processing and the TLS key schedule.

use std::ffi::c_int;
use std::sync::OnceLock;
use zeroize::Zeroizing;

type X448Callback = unsafe extern "C" fn(*mut u8, *const u8, *const u8) -> c_int;

unsafe extern "C" {
    fn SSL_set_bridge_x448_callback(callback: X448Callback) -> c_int;
}

/// Register a process-lifetime provider exactly once, before configuring TLS.
pub(crate) fn register() -> bool {
    static REGISTERED: OnceLock<bool> = OnceLock::new();
    *REGISTERED.get_or_init(|| {
        // SAFETY: the callback is a static function and implements the fixed
        // 56-byte input/output contract declared in the native patch.
        unsafe { SSL_set_bridge_x448_callback(x448) == 1 }
    })
}

/// The native caller guarantees nonoverlapping, readable/writable 56-byte
/// buffers. It rejects incorrect peer lengths before invoking this callback.
unsafe extern "C" fn x448(out: *mut u8, private_key: *const u8, peer: *const u8) -> c_int {
    if out.is_null() {
        return 0;
    }
    // SAFETY: out points to a writable 56-byte native buffer.
    unsafe { std::ptr::write_bytes(out, 0, 56) };
    if private_key.is_null() || peer.is_null() {
        return 0;
    }
    // Arrays of u8 have alignment 1. Native buffers live for the entire call.
    let private_key = Zeroizing::new(unsafe { std::ptr::read(private_key.cast::<[u8; 56]>()) });
    let peer = unsafe { std::ptr::read(peer.cast::<[u8; 56]>()) };
    let secret = Zeroizing::new(crrl::x448::x448(&peer, &private_key));
    // Accumulate every byte: no early exit dependent on the shared secret.
    // RFC 8446 requires aborting when X448 yields an all-zero shared secret.
    if secret.iter().fold(0u8, |acc, byte| acc | byte) == 0 {
        return 0;
    }
    // SAFETY: the output is distinct from the local 56-byte secret array.
    unsafe { std::ptr::copy_nonoverlapping(secret.as_ptr(), out, 56) };
    // Zeroizing clears our scalar and result copies. The native key-share
    // destructor separately clears the original scalar owned by BoringSSL.
    1
}

#[cfg(test)]
mod tests {
    use super::*;

    fn bytes(hex: &str) -> [u8; 56] {
        hex::decode(hex).unwrap().try_into().unwrap()
    }

    fn exchange(scalar: &[u8; 56], peer: &[u8; 56]) -> Option<[u8; 56]> {
        let mut out = [0xa5; 56];
        // SAFETY: all buffers have the required length and are disjoint.
        let ok = unsafe { x448(out.as_mut_ptr(), scalar.as_ptr(), peer.as_ptr()) };
        if ok == 1 {
            Some(out)
        } else {
            assert_eq!(out, [0; 56], "failed exchange exposed output");
            None
        }
    }

    #[test]
    fn rfc7748_x448_known_answers() {
        // RFC 7748 sections 5.2 and 6.2; expected values are not generated by
        // crrl or by the patched TLS backend.
        let cases = [
            (
                "3d262fddf9ec8e88495266fea19a34d28882acef045104d0d1aae121700a779c984c24f8cdd78fbff44943eba368f54b29259a4f1c600ad3",
                "06fce640fa3487bfda5f6cf2d5263f8aad88334cbd07437f020f08f9814dc031ddbdc38c19c6da2583fa5429db94ada18aa7a7fb4ef8a086",
                "ce3e4ff95a60dc6697da1db1d85e6afbdf79b50a2412d7546d5f239fe14fbaadeb445fc66a01b0779d98223961111e21766282f73dd96b6f",
            ),
            (
                "203d494428b8399352665ddca42f9de8fef600908e0d461cb021f8c538345dd77c3e4806e25f46d3315c44e0a5b4371282dd2c8d5be3095f",
                "0fbcc2f993cd56d3305b0b7d9e55d4c1a8fb5dbb52f8e9a1e9b6201b165d015894e56c4d3570bee52fe205e28a78b91cdfbde71ce8d157db",
                "884a02576239ff7a2f2f63b2db6a9ff37047ac13568e1e30fe63c4a7ad1b3ee3a5700df34321d62077e63633c575c1c954514e99da7c179d",
            ),
        ];
        for (scalar, peer, expected) in cases {
            assert_eq!(
                exchange(&bytes(scalar), &bytes(peer)),
                Some(bytes(expected))
            );
        }
        let alice = bytes("9a8f4925d1519f5775cf46b04b5800d4ee9ee8bae8bc5565d498c28dd9c9baf574a9419744897391006382a6f127ab1d9ac2d8c0a598726b");
        let alice_public = bytes("9b08f7cc31b7e3e67d22d5aea121074a273bd2b83de09c63faa73d2c22c5d9bbc836647241d953d40c5b12da88120d53177f80e532c41fa0");
        let bob = bytes("1c306a7ac2a0e2e0990b294470cba339e6453772b075811d8fad0d1d6927c120bb5ee8972b0d3e21374c9c921b09d1b0366f10b65173992d");
        let bob_public = bytes("3eb7a829b0cd20f5bcfc0b599b6feccf6da4627107bdb0d4f345b43027d8b972fc3e34fb4232a13ca706dcb57aec3dae07bdc1c67bf33609");
        let expected = bytes("07fff4181ac6cc95ec1c16a94a0f74d12da232ce40a77552281d282bb60c0b56fd2464c335543936521c24403085d59a449a5037514a879d");
        let mut base = [0; 56];
        base[0] = 5;
        assert_eq!(exchange(&alice, &base), Some(alice_public));
        assert_eq!(exchange(&bob, &base), Some(bob_public));
        assert_eq!(exchange(&alice, &bob_public), Some(expected));
        assert_eq!(exchange(&bob, &alice_public), Some(expected));
    }

    #[test]
    fn x448_rejects_low_order_peers_and_clears_output() {
        let scalar = [0x42; 56];
        let mut one = [0; 56];
        one[0] = 1;
        let mut p = [0xff; 56];
        p[28] = 0xfe;
        let mut p_minus_one = p;
        p_minus_one[0] -= 1;
        let mut p_plus_one = [0; 56];
        p_plus_one[28..].fill(0xff);
        for peer in [[0; 56], one, p_minus_one, p, p_plus_one] {
            assert_eq!(exchange(&scalar, &peer), None);
        }
        let mut out = [0xa5; 56];
        // SAFETY: the callback must reject null input pointers before reading.
        assert_eq!(
            unsafe { x448(out.as_mut_ptr(), std::ptr::null(), one.as_ptr()) },
            0
        );
        assert_eq!(out, [0; 56]);
    }

    #[test]
    fn x448_clamps_scalars_and_accepts_noncanonical_public_coordinates() {
        let scalar = [0x42; 56];
        let mut scalar_equivalent = scalar;
        scalar_equivalent[0] ^= 3;
        scalar_equivalent[55] ^= 128;
        let mut base = [0; 56];
        base[0] = 5;
        // p+5, congruent to the base point, MUST be accepted by RFC 7748.
        let mut p_plus_five = [0; 56];
        p_plus_five[0] = 4;
        p_plus_five[28..].fill(0xff);
        assert_eq!(
            exchange(&scalar, &base),
            exchange(&scalar_equivalent, &base)
        );
        assert_eq!(exchange(&scalar, &base), exchange(&scalar, &p_plus_five));
        // Unlike X25519, X448's public-coordinate top bit is significant.
        let mut high_bit = base;
        high_bit[55] = 128;
        assert_ne!(exchange(&scalar, &base), exchange(&scalar, &high_bit));
    }
}
